import type { TrainingModule } from '../lib/types';
import { MASCOT_LINES } from './copy';

// ═══════════════════════════════════════════════════════════════════════════════
// MODULE 1 — Why Security Matters
// ═══════════════════════════════════════════════════════════════════════════════

const module1: TrainingModule = {
  id: 'module-1',
  title: 'Why Security Matters',
  shortTitle: 'Your Role',
  objective: 'Understand that every employee is part of the security perimeter.',
  mascotIntro: MASCOT_LINES.module1Intro,
  mascotOutro: MASCOT_LINES.module1Outro,
  badgeIds: ['pack-protector'],
  interactions: [
    {
      type: 'info-card',
      id: 'm1-intro',
      title: 'Security starts with people',
      body: 'Most security incidents don\'t start with sophisticated hacking. They start with a click, a reused password, or a moment of distraction. Your awareness is the first and strongest line of defense.',
      mascotComment: MASCOT_LINES.module1Intro,
      bullets: [
        'Over 80% of breaches involve a human element.',
        'Attackers target people, not just systems.',
        'A single alert employee can stop an attack in its tracks.',
      ],
      icon: 'shield',
    },
    {
      type: 'multiple-choice',
      id: 'm1-q1',
      question: 'Who is responsible for helping keep the company secure?',
      context: 'Think about the role every person plays, not just the security team.',
      mascotHint: 'This one sets the tone for everything that follows.',
      options: [
        {
          id: 'm1-q1-a',
          label: 'Only the IT / security team',
          scoreImpact: 0,
          isCorrect: false,
          topicTags: ['security-role'],
          feedbackTitle: 'Not quite.',
          feedbackExplanation: 'The security team sets policies and tools, but they can\'t be everywhere. Every employee encounters risks daily.',
        },
        {
          id: 'm1-q1-b',
          label: 'Everyone plays a role',
          scoreImpact: 150,
          isCorrect: true,
          isBestPractice: true,
          topicTags: ['security-role'],
          feedbackTitle: 'Exactly right.',
          feedbackExplanation: 'Security is a shared responsibility. From recognizing a suspicious email to locking your screen, every action counts.',
          takeaway: 'Every employee is part of the security perimeter.',
        },
        {
          id: 'm1-q1-c',
          label: 'Management and executives only',
          scoreImpact: 0,
          isCorrect: false,
          topicTags: ['security-role'],
          feedbackTitle: 'Not quite.',
          feedbackExplanation: 'Leadership sets direction, but attackers target everyone — not just people with "manager" in their title.',
        },
        {
          id: 'm1-q1-d',
          label: 'Whoever handles customer data',
          scoreImpact: 0,
          isCorrect: false,
          topicTags: ['security-role'],
          feedbackTitle: 'Partially right, but not enough.',
          feedbackExplanation: 'Data handlers have extra responsibilities, but every employee can be a target or a first line of defense.',
        },
      ],
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// MODULE 2 — Protect Your Accounts
// ═══════════════════════════════════════════════════════════════════════════════

const module2: TrainingModule = {
  id: 'module-2',
  title: 'Protect Your Accounts',
  shortTitle: 'Passwords',
  objective: 'Learn to create strong passphrases, avoid reuse, and use a password manager.',
  mascotIntro: MASCOT_LINES.module2Intro,
  mascotOutro: MASCOT_LINES.module2Outro,
  badgeIds: ['password-hound'],
  interactions: [
    {
      type: 'info-card',
      id: 'm2-intro',
      title: 'Your accounts are the front door',
      body: 'A weak or reused password is like using the same key for your house, office, and car — and leaving copies everywhere.',
      mascotComment: MASCOT_LINES.module2Intro,
      bullets: [
        'Length beats complexity. A 4-word passphrase is stronger than "P@ssw0rd!".',
        'Every account should have a unique password.',
        'A password manager handles the hard part for you.',
      ],
    },
    {
      type: 'multiple-choice',
      id: 'm2-q1-password-strength',
      question: 'Which of these is the strongest password?',
      context: 'Think about length, randomness, and uniqueness.',
      mascotHint: 'A strong password helps protect the pack.',
      options: [
        {
          id: 'm2-q1-a',
          label: 'P@ssw0rd123!',
          scoreImpact: -50,
          isCorrect: false,
          topicTags: ['password-strength'],
          feedbackTitle: 'This is one of the most commonly guessed passwords.',
          feedbackExplanation: 'Replacing letters with symbols (a→@, o→0) is a well-known pattern. Attackers check these first.',
        },
        {
          id: 'm2-q1-b',
          label: 'locate-shark-fuzzy-bean',
          scoreImpact: 150,
          isCorrect: true,
          isBestPractice: true,
          topicTags: ['password-strength'],
          feedbackTitle: 'Excellent choice.',
          feedbackExplanation: 'A random 4-word passphrase is long, hard to guess, and easy to remember. This is the gold standard.',
          takeaway: 'Use long, random, unique passphrases for each account.',
        },
        {
          id: 'm2-q1-c',
          label: 'MyDogMax2024',
          scoreImpact: 0,
          isCorrect: false,
          topicTags: ['password-strength'],
          feedbackTitle: 'Too personal and predictable.',
          feedbackExplanation: 'Names, pets, and years are easy to find on social media. Attackers use this kind of info in targeted guesses.',
        },
        {
          id: 'm2-q1-d',
          label: 'aX9$kL2!',
          scoreImpact: 0,
          isCorrect: false,
          topicTags: ['password-strength'],
          feedbackTitle: 'Complex but too short.',
          feedbackExplanation: 'Eight characters can be brute-forced quickly regardless of complexity. Length is more important than special characters.',
        },
      ],
    },
    {
      type: 'branching-scenario',
      id: 'm2-reuse-scenario',
      title: 'The Reuse Trap',
      context: 'You used the same password for a personal shopping site and your work email. The shopping site just announced a data breach.',
      mascotHint: 'One breach can open many doors when passwords are reused.',
      topicTags: ['password-reuse', 'credential-stuffing'],
      startStepId: 'step-1',
      steps: [
        {
          id: 'step-1',
          narrative: 'You receive a news alert: a shopping site you use has been breached. Millions of email/password combos were leaked. You used the same password for your work account. What do you do first?',
          choices: [
            {
              id: 'reuse-1a',
              label: 'Ignore it — it was just a shopping site',
              scoreImpact: -50,
              isCorrect: false,
              topicTags: ['password-reuse', 'credential-stuffing'],
              feedbackTitle: 'Risky choice.',
              feedbackExplanation: 'Attackers use leaked credentials to try logging into other services. This is called credential stuffing. Your work account is now at risk.',
            },
            {
              id: 'reuse-1b',
              label: 'Change your work password immediately and make it unique',
              scoreImpact: 100,
              isCorrect: true,
              topicTags: ['password-reuse'],
              feedbackTitle: 'Good move.',
              feedbackExplanation: 'Changing to a unique password stops credential stuffing from working. Each account should have its own password.',
              nextStepId: 'step-2',
            },
            {
              id: 'reuse-1c',
              label: 'Change your work password and report it to IT',
              scoreImpact: 150,
              isCorrect: true,
              isBestPractice: true,
              reportBonus: true,
              topicTags: ['password-reuse', 'credential-stuffing'],
              feedbackTitle: 'Best-practice response.',
              feedbackExplanation: 'You fixed the immediate risk and alerted the team. IT can check for suspicious login attempts on your account.',
              takeaway: 'When a breach affects a reused password, change it and notify your security team.',
              nextStepId: 'step-2',
            },
          ],
        },
        {
          id: 'step-2',
          narrative: 'IT asks how many other accounts share that same password. You realize you used it on three more services. What\'s your next step?',
          mascotComment: 'This is where a password manager pays off.',
          choices: [
            {
              id: 'reuse-2a',
              label: 'Change them all to unique passwords using a password manager',
              scoreImpact: 150,
              isCorrect: true,
              isBestPractice: true,
              topicTags: ['password-reuse', 'password-manager'],
              feedbackTitle: 'Perfect approach.',
              feedbackExplanation: 'A password manager generates and stores unique passwords for every account. No more reuse, no more memorizing.',
              takeaway: 'A password manager eliminates password reuse entirely.',
            },
            {
              id: 'reuse-2b',
              label: 'Change them to different passwords you can remember',
              scoreImpact: 100,
              isCorrect: true,
              topicTags: ['password-reuse'],
              feedbackTitle: 'Good — you\'re stopping the reuse.',
              feedbackExplanation: 'Unique passwords per account is the right idea. A password manager makes this sustainable long-term.',
            },
            {
              id: 'reuse-2c',
              label: 'Just change the work one — the others don\'t matter',
              scoreImpact: 0,
              isCorrect: false,
              topicTags: ['password-reuse'],
              feedbackTitle: 'Half the job.',
              feedbackExplanation: 'Those other accounts could also be compromised. Credential stuffing attacks try every service they can find.',
            },
          ],
        },
      ],
    },
    {
      type: 'multiple-choice',
      id: 'm2-q2-password-manager',
      question: 'How does a password manager help protect you from fake login pages?',
      context: 'An attacker has created a convincing copy of your company\'s login page at "yourcompanny-login.com" (note the typo).',
      mascotHint: 'Password managers are smarter than they look.',
      options: [
        {
          id: 'm2-q2-a',
          label: 'It checks the URL before autofilling — a fake domain won\'t match',
          scoreImpact: 150,
          isCorrect: true,
          isBestPractice: true,
          topicTags: ['password-manager', 'phishing'],
          feedbackTitle: 'Exactly right.',
          feedbackExplanation: 'Password managers match credentials to specific domains. If the URL doesn\'t match, it won\'t autofill — alerting you to a potential fake.',
          takeaway: 'A password manager catches fake sites your eyes might miss.',
        },
        {
          id: 'm2-q2-b',
          label: 'It encrypts your password so attackers can\'t read it',
          scoreImpact: 0,
          isCorrect: false,
          topicTags: ['password-manager'],
          feedbackTitle: 'That\'s a benefit, but not the key one here.',
          feedbackExplanation: 'Encryption protects stored passwords, but the anti-phishing power comes from domain matching. If you\'re on a fake site, the manager won\'t fill in your credentials.',
        },
        {
          id: 'm2-q2-c',
          label: 'It blocks all suspicious websites automatically',
          scoreImpact: 0,
          isCorrect: false,
          topicTags: ['password-manager'],
          feedbackTitle: 'That\'s not what it does.',
          feedbackExplanation: 'Password managers don\'t block sites. But they refuse to autofill on domains that don\'t match — which is a strong signal something is wrong.',
        },
        {
          id: 'm2-q2-d',
          label: 'It doesn\'t — you still have to check the URL yourself',
          scoreImpact: 0,
          isCorrect: false,
          topicTags: ['password-manager'],
          feedbackTitle: 'You should always check, but the manager helps too.',
          feedbackExplanation: 'Good habit to verify URLs, but password managers add an automated layer. If autofill doesn\'t trigger, that\'s your cue to look closer.',
        },
      ],
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// MODULE 3 — MFA / Stronger Login Protection
// ═══════════════════════════════════════════════════════════════════════════════

const module3: TrainingModule = {
  id: 'module-3',
  title: 'MFA & Stronger Login Protection',
  shortTitle: 'MFA',
  objective: 'Understand multi-factor authentication and why some methods are stronger than others.',
  mascotIntro: MASCOT_LINES.module3Intro,
  mascotOutro: MASCOT_LINES.module3Outro,
  badgeIds: ['mfa-guard'],
  interactions: [
    {
      type: 'info-card',
      id: 'm3-intro',
      title: 'Something you know, have, or are',
      body: 'MFA means using two or more different types of proof when logging in. Even if someone steals your password, they still can\'t get in without the second factor.',
      mascotComment: MASCOT_LINES.module3Intro,
      bullets: [
        'Something you know — password, PIN, security question.',
        'Something you have — phone, hardware token, authenticator app.',
        'Something you are — fingerprint, face scan, voice.',
      ],
      icon: 'lock',
    },
    {
      type: 'sort',
      id: 'm3-rank-mfa',
      question: 'Rank these MFA methods from strongest to weakest.',
      context: 'Not all second factors are created equal. Some are much harder for attackers to intercept.',
      mascotHint: 'Think about what an attacker would need to steal or intercept.',
      items: [
        { id: 'mfa-hardware', label: 'Hardware security key', description: 'A physical device you plug in or tap (e.g., YubiKey).' },
        { id: 'mfa-auth-app', label: 'Authenticator app', description: 'Time-based codes generated on your phone (e.g., Google Authenticator).' },
        { id: 'mfa-biometric', label: 'Biometrics (fingerprint / face scan)', description: 'Your fingerprint or face scan on a trusted device.' },
        { id: 'mfa-sms', label: 'SMS text message code', description: 'A code sent via text message to your phone number.' },
        { id: 'mfa-email', label: 'Email code', description: 'A verification code sent to your email inbox.' },
      ],
      correctOrder: ['mfa-hardware', 'mfa-auth-app', 'mfa-biometric', 'mfa-sms', 'mfa-email'],
      feedbackCorrect: 'Perfect ranking. Hardware keys and authenticator apps are the strongest because they can\'t be intercepted remotely. SMS and email are better than nothing, but vulnerable to interception.',
      feedbackIncorrect: 'Not quite right. Hardware keys are strongest (can\'t be phished), followed by authenticator apps and biometrics. SMS is weaker because of SIM swap attacks, and email codes are the easiest to intercept.',
      perfectScore: 150,
      partialScore: 75,
      topicTags: ['mfa-methods'],
    },
    {
      type: 'branching-scenario',
      id: 'm3-credential-stuffing',
      title: 'Credential Stuffing Attack',
      context: 'You get a security alert: someone tried to log into your work account from an unfamiliar location. The attempt used your correct password.',
      mascotHint: 'If they have your password, the question is: do they have more?',
      topicTags: ['credential-stuffing', 'mfa-methods'],
      startStepId: 'cs-1',
      steps: [
        {
          id: 'cs-1',
          narrative: 'A login attempt was blocked because it came from an unexpected country, but the correct password was used. What\'s your first action?',
          choices: [
            {
              id: 'cs-1a',
              label: 'Change your password immediately and enable MFA',
              scoreImpact: 150,
              isCorrect: true,
              isBestPractice: true,
              reportBonus: true,
              topicTags: ['credential-stuffing', 'mfa-methods'],
              feedbackTitle: 'Best response.',
              feedbackExplanation: 'Changing the password stops the leaked credential from working. MFA ensures that even if it happens again, the attacker still can\'t get in.',
              takeaway: 'MFA protects you even if your password is stolen.',
            },
            {
              id: 'cs-1b',
              label: 'Ignore it — the system blocked it already',
              scoreImpact: -50,
              isCorrect: false,
              topicTags: ['credential-stuffing'],
              feedbackTitle: 'Dangerous assumption.',
              feedbackExplanation: 'The block was lucky — they had your correct password. Next time they might try from a more believable location, or target other accounts with the same password.',
            },
            {
              id: 'cs-1c',
              label: 'Change your password',
              scoreImpact: 100,
              isCorrect: true,
              topicTags: ['credential-stuffing'],
              feedbackTitle: 'Good start, but not complete.',
              feedbackExplanation: 'A new password stops this specific attack. But without MFA, another leaked password in the future leaves you exposed again.',
            },
          ],
        },
      ],
    },
    {
      type: 'multiple-choice',
      id: 'm3-sim-swap',
      question: 'Why is SMS-based MFA considered weaker than an authenticator app?',
      context: 'A colleague argues that texting a code to your phone is "good enough." Here\'s the risk they might not know about.',
      mascotHint: 'Your phone number can be stolen without touching your phone.',
      options: [
        {
          id: 'sim-a',
          label: 'Attackers can trick your carrier into transferring your number (SIM swap)',
          scoreImpact: 150,
          isCorrect: true,
          isBestPractice: true,
          topicTags: ['sim-swap', 'mfa-methods'],
          feedbackTitle: 'Correct.',
          feedbackExplanation: 'In a SIM swap attack, someone convinces your phone carrier to move your number to their SIM card. They then receive all your SMS codes. Authenticator apps live on your device and can\'t be transferred this way.',
          takeaway: 'SMS codes can be intercepted via SIM swap. Prefer authenticator apps or hardware keys.',
        },
        {
          id: 'sim-b',
          label: 'SMS codes expire too quickly',
          scoreImpact: 0,
          isCorrect: false,
          topicTags: ['mfa-methods'],
          feedbackTitle: 'That\'s not the main risk.',
          feedbackExplanation: 'Expiration is actually a feature. The real weakness is that SMS messages can be intercepted or redirected.',
        },
        {
          id: 'sim-c',
          label: 'Text messages use too much battery',
          scoreImpact: 0,
          isCorrect: false,
          topicTags: ['mfa-methods'],
          feedbackTitle: 'Not a security concern.',
          feedbackExplanation: 'The weakness of SMS MFA is about interception, not convenience.',
        },
        {
          id: 'sim-d',
          label: 'Authenticator apps and SMS are equally secure',
          scoreImpact: 0,
          isCorrect: false,
          topicTags: ['sim-swap', 'mfa-methods'],
          feedbackTitle: 'They\'re not equal.',
          feedbackExplanation: 'SMS is better than no MFA, but authenticator apps are significantly harder to compromise because codes never leave your device.',
        },
      ],
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// MODULE 4 — Spot Threats
// ═══════════════════════════════════════════════════════════════════════════════

const module4: TrainingModule = {
  id: 'module-4',
  title: 'Spot Threats',
  shortTitle: 'Threats',
  objective: 'Identify phishing, social engineering, malware, and risky delivery methods.',
  mascotIntro: MASCOT_LINES.module4Intro,
  mascotOutro: MASCOT_LINES.module4Outro,
  badgeIds: ['threat-sniffer'],
  interactions: [
    {
      type: 'inbox',
      id: 'm4-inbox',
      question: 'Review your inbox. Mark each message as Safe, Suspicious, or Report it.',
      context: 'You arrive at your desk to find several new messages. Some are legitimate, some are not.',
      mascotHint: 'Check the sender address, the urgency, and the links carefully.',
      correctMarkScore: 100,
      correctSafeScore: 100,
      reportBonusScore: 50,
      wrongOpenPenalty: -50,
      messages: [
        {
          id: 'inbox-1',
          from: 'IT Support',
          fromEmail: 'it-support@yourcompany.com',
          subject: 'Scheduled maintenance this Saturday',
          preview: 'Hi team, we\'ll be performing scheduled server maintenance this Saturday from 2-6 AM. No action needed on your end.',
          timestamp: '9:02 AM',
          isSuspicious: false,
          redFlags: [],
          topicTags: ['phishing'],
        },
        {
          id: 'inbox-2',
          from: 'HR Department',
          fromEmail: 'hr-noreply@yourcompanny.com',
          subject: 'URGENT: Verify your direct deposit info NOW',
          preview: 'Your payroll information needs immediate verification. Click here to confirm your bank details or your next payment may be delayed.',
          timestamp: '9:15 AM',
          isSuspicious: true,
          redFlags: [
            'Misspelled domain: "yourcompanny.com" (double n)',
            'Creates false urgency about payroll',
            'Asks you to click a link to enter bank details',
          ],
          topicTags: ['phishing'],
        },
        {
          id: 'inbox-3',
          from: 'Sarah Chen',
          fromEmail: 'sarah.chen@yourcompany.com',
          subject: 'Q3 planning doc — feedback needed',
          preview: 'Hey, attached is the Q3 planning doc we discussed in standup. Can you review section 3 and send comments by Friday?',
          timestamp: '10:30 AM',
          isSuspicious: false,
          redFlags: [],
          topicTags: ['phishing'],
        },
        {
          id: 'inbox-4',
          from: 'Microsoft 365',
          fromEmail: 'security-alert@microsoft365-verify.net',
          subject: 'Your account will be suspended in 24 hours',
          preview: 'We detected unusual activity on your Microsoft 365 account. Verify your identity immediately to prevent suspension.',
          timestamp: '11:05 AM',
          isSuspicious: true,
          redFlags: [
            'External domain: "microsoft365-verify.net" is not Microsoft',
            'Threatens account suspension to create panic',
            'Asks for immediate identity verification via link',
          ],
          topicTags: ['phishing'],
        },
        {
          id: 'inbox-5',
          from: 'CEO - James Mitchell',
          fromEmail: 'james.mitchell.ceo@gmail.com',
          subject: 'Quick favor — confidential',
          preview: 'Are you available? I need you to purchase some gift cards for a client meeting. Will explain later. Please keep this between us.',
          timestamp: '2:30 PM',
          isSuspicious: true,
          redFlags: [
            'Personal Gmail address, not company email',
            'Gift card request is a classic scam',
            'Asks for secrecy ("keep this between us")',
            'Urgency without context',
          ],
          topicTags: ['phishing', 'social-engineering'],
        },
        {
          id: 'inbox-6',
          from: 'Jira',
          fromEmail: 'notifications@atlassian.net',
          subject: 'PROJ-1234 assigned to you',
          preview: 'Sarah Chen assigned PROJ-1234 "Update API rate limiting" to you. Due date: Friday.',
          timestamp: '3:15 PM',
          isSuspicious: false,
          redFlags: [],
          topicTags: ['phishing'],
        },
      ],
    },
    {
      type: 'branching-scenario',
      id: 'm4-social-engineering',
      title: 'The Urgent Request',
      context: 'You receive a phone call from someone claiming to be from your company\'s IT department.',
      mascotHint: 'That message feels urgent on purpose.',
      topicTags: ['social-engineering'],
      startStepId: 'se-1',
      steps: [
        {
          id: 'se-1',
          narrative: 'A caller says: "Hi, this is Mike from IT. We\'re dealing with a critical security incident and need to verify your account. Can you confirm your password so I can check if your account was compromised?"',
          mascotComment: 'Legitimate IT staff will never ask for your password over the phone.',
          choices: [
            {
              id: 'se-1a',
              label: 'Share your password — it sounds urgent',
              scoreImpact: -50,
              isCorrect: false,
              topicTags: ['social-engineering'],
              feedbackTitle: 'Never share your password.',
              feedbackExplanation: 'No legitimate IT person will ever ask for your password. This is a classic social engineering tactic using urgency and authority.',
            },
            {
              id: 'se-1b',
              label: 'Ask for their employee ID and call IT through the official number',
              scoreImpact: 150,
              isCorrect: true,
              isBestPractice: true,
              topicTags: ['social-engineering'],
              feedbackTitle: 'Perfect response.',
              feedbackExplanation: 'Verifying identity through a separate, trusted channel is the gold standard. A real IT person will understand and appreciate this.',
              takeaway: 'Always verify unexpected requests through a separate trusted channel.',
              nextStepId: 'se-2',
            },
            {
              id: 'se-1c',
              label: 'Politely decline and hang up',
              scoreImpact: 100,
              isCorrect: true,
              topicTags: ['social-engineering'],
              feedbackTitle: 'Good instinct.',
              feedbackExplanation: 'Refusing to share credentials is the right call. Even better: verify who they are by calling IT directly.',
              nextStepId: 'se-2',
            },
          ],
        },
        {
          id: 'se-2',
          narrative: 'You called IT through the official number. They confirm no one named Mike works there and no incident is happening. What do you do now?',
          choices: [
            {
              id: 'se-2a',
              label: 'Report the call to the security team',
              scoreImpact: 150,
              isCorrect: true,
              isBestPractice: true,
              reportBonus: true,
              topicTags: ['social-engineering'],
              feedbackTitle: 'Best response.',
              feedbackExplanation: 'Reporting helps the security team warn others and investigate if someone is targeting the company.',
              takeaway: 'Report social engineering attempts — others may be targeted too.',
            },
            {
              id: 'se-2b',
              label: 'Move on — the threat is handled',
              scoreImpact: 100,
              isCorrect: true,
              topicTags: ['social-engineering'],
              feedbackTitle: 'The immediate threat is handled.',
              feedbackExplanation: 'You protected yourself, but reporting helps protect everyone else. The attacker might call your colleagues next.',
            },
          ],
        },
      ],
    },
    {
      type: 'sort',
      id: 'm4-delivery-methods',
      question: 'Sort these into the correct risk category.',
      context: 'Different delivery methods carry different risk levels. Categorize each one.',
      mascotHint: 'If you didn\'t ask for it and don\'t recognize the source, be cautious.',
      items: [
        { id: 'dm-usb', label: 'USB drive found in the parking lot', description: 'Someone left a thumb drive near the entrance.' },
        { id: 'dm-ad', label: 'Browser ad offering free software', description: '"Download this free PDF editor — no signup needed!"' },
        { id: 'dm-update', label: 'Managed software update notification', description: 'Your IT-approved update tool says a new version is available.' },
        { id: 'dm-attach', label: 'Unexpected email attachment from unknown sender', description: 'An invoice PDF from a company you don\'t recognize.' },
        { id: 'dm-appstore', label: 'App from the company-approved app catalog', description: 'Slack update from your managed software center.' },
      ],
      correctOrder: ['dm-appstore', 'dm-update', 'dm-attach', 'dm-ad', 'dm-usb'],
      feedbackCorrect: 'Well done. Company-approved sources are safest. Unknown USBs and random browser downloads are the most dangerous.',
      feedbackIncorrect: 'Not quite. The safest sources are company-managed. Unknown USB drives are extremely risky — they could contain malware that runs automatically.',
      perfectScore: 150,
      partialScore: 75,
      topicTags: ['suspicious-downloads', 'malware'],
    },
    {
      type: 'multiple-choice',
      id: 'm4-malware-response',
      question: 'You click a link and your screen starts showing strange pop-ups demanding payment to unlock your files. What do you do first?',
      context: 'This looks like a ransomware attack.',
      mascotHint: 'Speed matters here, but not the kind the attacker wants.',
      options: [
        {
          id: 'mal-a',
          label: 'Disconnect from the network immediately',
          scoreImpact: 150,
          isCorrect: true,
          isBestPractice: true,
          topicTags: ['malware'],
          feedbackTitle: 'Exactly right.',
          feedbackExplanation: 'Disconnecting limits the ransomware\'s ability to spread to other devices on the network. Then report to IT immediately.',
          takeaway: 'If you suspect malware: disconnect, stop interacting, report.',
        },
        {
          id: 'mal-b',
          label: 'Pay the ransom to get your files back',
          scoreImpact: -50,
          isCorrect: false,
          topicTags: ['malware'],
          feedbackTitle: 'Never pay the ransom.',
          feedbackExplanation: 'Payment doesn\'t guarantee file recovery and funds criminal operations. Disconnect and let IT handle recovery from backups.',
        },
        {
          id: 'mal-c',
          label: 'Try to close the pop-ups and continue working',
          scoreImpact: -50,
          isCorrect: false,
          topicTags: ['malware'],
          feedbackTitle: 'Don\'t keep interacting.',
          feedbackExplanation: 'Clicking more things could make it worse. The ransomware may already be encrypting files. Disconnect first.',
        },
        {
          id: 'mal-d',
          label: 'Turn off the computer completely',
          scoreImpact: 100,
          isCorrect: true,
          topicTags: ['malware'],
          feedbackTitle: 'Better than continuing, but not ideal.',
          feedbackExplanation: 'Shutting down stops the attack, but IT may need the machine running (but disconnected) for forensics. Disconnect from the network first if you can.',
        },
      ],
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// MODULE 5 — Devices + Sensitive Information
// ═══════════════════════════════════════════════════════════════════════════════

const module5: TrainingModule = {
  id: 'module-5',
  title: 'Devices & Sensitive Information',
  shortTitle: 'Devices & Data',
  objective: 'Keep devices secure, handle sensitive data carefully, and maintain clean workspaces.',
  mascotIntro: MASCOT_LINES.module5Intro,
  mascotOutro: MASCOT_LINES.module5Outro,
  badgeIds: ['device-defender', 'data-guardian'],
  interactions: [
    {
      type: 'multiple-choice',
      id: 'm5-lock-screen',
      question: 'You need to step away from your desk for a quick coffee. Your laptop is open with Slack and a customer dashboard visible. What do you do?',
      mascotHint: 'It only takes a few seconds — for you and for someone who shouldn\'t be looking.',
      options: [
        {
          id: 'lock-a',
          label: 'Lock your screen before standing up (Cmd+L / Win+L)',
          scoreImpact: 150,
          isCorrect: true,
          isBestPractice: true,
          topicTags: ['device-locking'],
          feedbackTitle: 'Good habit.',
          feedbackExplanation: 'Locking your screen is fast, automatic with practice, and prevents unauthorized access to everything visible.',
          takeaway: 'Lock your device every time you step away — even for a minute.',
        },
        {
          id: 'lock-b',
          label: 'Leave it open — you\'ll only be a minute',
          scoreImpact: -50,
          isCorrect: false,
          topicTags: ['device-locking'],
          feedbackTitle: 'A minute is enough.',
          feedbackExplanation: 'Visitors, cleaning staff, or even well-meaning colleagues could see sensitive customer data. Locking takes less than a second.',
        },
        {
          id: 'lock-c',
          label: 'Close the laptop lid',
          scoreImpact: 100,
          isCorrect: true,
          topicTags: ['device-locking'],
          feedbackTitle: 'Effective, but check your settings.',
          feedbackExplanation: 'Closing the lid works if it\'s configured to lock. Some laptops just sleep without requiring a password to reopen. Verify your settings.',
        },
      ],
    },
    {
      type: 'multiple-choice',
      id: 'm5-software-update',
      question: 'You see two update notifications. Which one should you trust?',
      context: 'Notification A: Your company\'s managed software center shows "Chrome 120 update available — Install now."\n\nNotification B: A browser pop-up says "CRITICAL: Your Chrome is out of date! Click here to download the latest version immediately."',
      mascotHint: 'Legitimate updates come from expected places.',
      options: [
        {
          id: 'update-a',
          label: 'Trust the managed software center (Notification A)',
          scoreImpact: 150,
          isCorrect: true,
          isBestPractice: true,
          topicTags: ['software-updates', 'approved-software'],
          feedbackTitle: 'Correct.',
          feedbackExplanation: 'Updates from your managed software center are vetted by IT. Random browser pop-ups demanding immediate downloads are a classic malware trick.',
          takeaway: 'Always update through your official managed update channel.',
        },
        {
          id: 'update-b',
          label: 'Trust the browser pop-up (Notification B) — it says critical',
          scoreImpact: -50,
          isCorrect: false,
          topicTags: ['software-updates', 'suspicious-downloads'],
          feedbackTitle: 'That\'s likely malware.',
          feedbackExplanation: 'Fake update pop-ups are one of the most common malware delivery methods. Legitimate updates don\'t use aggressive pop-ups.',
        },
        {
          id: 'update-c',
          label: 'Ignore both — updates can wait',
          scoreImpact: 0,
          isCorrect: false,
          topicTags: ['software-updates'],
          feedbackTitle: 'Don\'t skip legitimate updates.',
          feedbackExplanation: 'Security updates patch known vulnerabilities. Delaying them leaves you exposed to attacks that have already been fixed.',
        },
      ],
    },
    {
      type: 'sort',
      id: 'm5-data-sorter',
      question: 'Categorize each action: Safe, Needs Approval, or Unsafe.',
      context: 'Handling sensitive data correctly means knowing what\'s okay, what needs a check, and what should never happen.',
      mascotHint: 'When in doubt, treat it as sensitive and check first.',
      items: [
        { id: 'data-1', label: 'Storing project files in the company-approved cloud drive', description: 'Using Google Drive / SharePoint managed by IT.' },
        { id: 'data-2', label: 'Emailing a customer list to your personal email', description: 'You want to work on it from home over the weekend.' },
        { id: 'data-3', label: 'Sharing a sanitized performance metric in a team Slack channel', description: 'No customer PII, just aggregate numbers.' },
        { id: 'data-4', label: 'Posting a screenshot of internal tooling on social media', description: 'You\'re excited about a new feature the team built.' },
        { id: 'data-5', label: 'Exporting customer data for a report, then deleting the export when done', description: 'Your manager approved the export for a quarterly review.' },
      ],
      correctOrder: ['data-1', 'data-3', 'data-5', 'data-4', 'data-2'],
      feedbackCorrect: 'Great categorization. Internal tools for internal data, approval for exports, and never send sensitive data to personal accounts.',
      feedbackIncorrect: 'Review the principle: keep data in approved systems, get approval for exports, never send to personal accounts, and be careful about public sharing of internal tools.',
      perfectScore: 150,
      partialScore: 75,
      topicTags: ['sensitive-data'],
    },
    {
      type: 'hotspot-scene',
      id: 'm5-office-hotspot',
      question: 'Find the security risks in this office scene.',
      context: 'You\'re walking through the office after hours. Spot everything that could be a security risk.',
      mascotHint: 'Look for anything that shouldn\'t be visible or accessible.',
      sceneAltText: 'An open-plan office with several desks. Some desks have items left on them that pose security risks.',
      sceneDescription: 'Office scene with multiple workstations, a whiteboard, a printer area, and a meeting room visible through glass walls.',
      requiredFinds: 4,
      topicTags: ['clean-desk', 'device-locking', 'sensitive-data'],
      zones: [
        {
          id: 'hz-whiteboard',
          label: 'Whiteboard with project details',
          x: 5,
          y: 10,
          width: 25,
          height: 35,
          isRisk: true,
          feedbackTitle: 'Good catch — sensitive info on the whiteboard.',
          feedbackExplanation: 'Whiteboards in shared spaces can contain project names, architecture diagrams, or customer details visible to visitors. Erase sensitive content after meetings.',
          scoreImpact: 100,
          topicTags: ['clean-desk'],
        },
        {
          id: 'hz-printout',
          label: 'Printed documents left at printer',
          x: 65,
          y: 15,
          width: 20,
          height: 25,
          isRisk: true,
          feedbackTitle: 'Risk — uncollected printouts.',
          feedbackExplanation: 'Documents left at the printer can be picked up by anyone. Collect printouts immediately and shred sensitive documents when done.',
          scoreImpact: 100,
          topicTags: ['clean-desk', 'sensitive-data'],
        },
        {
          id: 'hz-laptop',
          label: 'Unlocked laptop at an empty desk',
          x: 35,
          y: 45,
          width: 20,
          height: 25,
          isRisk: true,
          feedbackTitle: 'Unlocked and unattended.',
          feedbackExplanation: 'An unlocked laptop gives anyone full access to email, Slack, customer data, and internal tools. Always lock when stepping away.',
          scoreImpact: 100,
          topicTags: ['device-locking'],
        },
        {
          id: 'hz-sticky',
          label: 'Sticky note with password on monitor',
          x: 55,
          y: 50,
          width: 12,
          height: 15,
          isRisk: true,
          feedbackTitle: 'A password on a sticky note.',
          feedbackExplanation: 'Writing passwords down and leaving them visible defeats the purpose of having a password. Use a password manager instead.',
          scoreImpact: 100,
          topicTags: ['clean-desk', 'password-strength'],
        },
        {
          id: 'hz-plant',
          label: 'Office plant on desk',
          x: 85,
          y: 55,
          width: 12,
          height: 20,
          isRisk: false,
          feedbackTitle: 'Just a plant.',
          feedbackExplanation: 'Plants are fine. Keep looking for actual security risks.',
          scoreImpact: 0,
          topicTags: [],
        },
        {
          id: 'hz-meeting-notes',
          label: 'Meeting notes with client names visible through glass wall',
          x: 5,
          y: 55,
          width: 22,
          height: 30,
          isRisk: true,
          feedbackTitle: 'Confidential info visible through glass.',
          feedbackExplanation: 'Meeting rooms with glass walls can expose sensitive information to passersby. Turn whiteboards away from windows or use privacy film.',
          scoreImpact: 100,
          topicTags: ['clean-desk', 'sensitive-data'],
        },
      ],
    },
    {
      type: 'multiple-choice',
      id: 'm5-remote-privacy',
      question: 'You\'re working from a coffee shop and need to join a video call discussing a client project. What\'s the safest approach?',
      mascotHint: 'Think about what people around you can see and hear.',
      options: [
        {
          id: 'remote-a',
          label: 'Use headphones, a privacy screen, and keep your voice low',
          scoreImpact: 150,
          isCorrect: true,
          isBestPractice: true,
          topicTags: ['remote-privacy'],
          feedbackTitle: 'Best approach for public spaces.',
          feedbackExplanation: 'Headphones protect audio leaks, a privacy screen blocks visual snooping, and keeping your voice low minimizes what others overhear.',
          takeaway: 'In public: headphones, privacy screen, low voice, and screen angled away.',
        },
        {
          id: 'remote-b',
          label: 'Put the call on speakerphone so you can multitask',
          scoreImpact: -50,
          isCorrect: false,
          topicTags: ['remote-privacy'],
          feedbackTitle: 'Everyone around you can hear the call.',
          feedbackExplanation: 'Speakerphone in a public space means anyone nearby hears client names, project details, and internal discussions.',
        },
        {
          id: 'remote-c',
          label: 'Reschedule the call for when you\'re in a private space',
          scoreImpact: 100,
          isCorrect: true,
          topicTags: ['remote-privacy'],
          feedbackTitle: 'A valid option when the topic is very sensitive.',
          feedbackExplanation: 'For highly confidential discussions, a private space is best. For routine calls, headphones and a privacy screen are usually sufficient.',
        },
      ],
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// FINAL CHALLENGE — Busy Workday
// ═══════════════════════════════════════════════════════════════════════════════

const finalChallenge: TrainingModule = {
  id: 'final-challenge',
  title: 'Final Challenge: Busy Workday',
  shortTitle: 'Final Challenge',
  objective: 'Make quick security decisions under time pressure.',
  mascotIntro: MASCOT_LINES.finalChallengeIntro,
  mascotOutro: MASCOT_LINES.finalChallengeOutro,
  badgeIds: ['top-watchdog'],
  interactions: [
    {
      type: 'timed-decision',
      id: 'fc-busy-day',
      title: 'Busy Workday',
      context: 'It\'s a hectic day. Several situations need your attention. Make quick, safe decisions.',
      mascotHint: 'Stay sharp. Pause, verify, and report when something feels off.',
      timeLimitSeconds: 180,
      topicTags: [],
      items: [
        {
          id: 'fc-1',
          scenario: 'You get a Slack DM from "IT Admin" asking you to click a link and reset your password because of a "detected breach."',
          options: [
            {
              id: 'fc-1a',
              label: 'Click the link and reset your password',
              scoreImpact: -50,
              isCorrect: false,
              topicTags: ['phishing'],
              feedbackTitle: 'Don\'t click.',
              feedbackExplanation: 'Legitimate password resets come through official channels, not random Slack DMs.',
            },
            {
              id: 'fc-1b',
              label: 'Verify by contacting IT through official channels',
              scoreImpact: 150,
              isCorrect: true,
              isBestPractice: true,
              reportBonus: true,
              topicTags: ['phishing', 'social-engineering'],
              feedbackTitle: 'Perfect.',
              feedbackExplanation: 'Verifying through a separate channel protects you from phishing attempts.',
            },
            {
              id: 'fc-1c',
              label: 'Ignore the message',
              scoreImpact: 100,
              isCorrect: true,
              topicTags: ['phishing'],
              feedbackTitle: 'Safe but incomplete.',
              feedbackExplanation: 'You avoided the risk, but reporting helps protect your teammates too.',
            },
          ],
        },
        {
          id: 'fc-2',
          scenario: 'A colleague left a USB drive on your desk with a note: "Presentation files for tomorrow\'s client meeting — please review."',
          options: [
            {
              id: 'fc-2a',
              label: 'Plug it in — your colleague needs help',
              scoreImpact: -50,
              isCorrect: false,
              topicTags: ['suspicious-downloads', 'malware'],
              feedbackTitle: 'Risky.',
              feedbackExplanation: 'Even a colleague\'s USB could be compromised without their knowledge. Use shared drives or ask them to send files digitally.',
            },
            {
              id: 'fc-2b',
              label: 'Ask the colleague directly and suggest sharing via the company drive',
              scoreImpact: 150,
              isCorrect: true,
              isBestPractice: true,
              topicTags: ['suspicious-downloads'],
              feedbackTitle: 'Best approach.',
              feedbackExplanation: 'Verify the source and use approved file-sharing methods. USB drives can carry malware even if the owner doesn\'t know.',
            },
            {
              id: 'fc-2c',
              label: 'Hand it to IT to scan first',
              scoreImpact: 100,
              isCorrect: true,
              topicTags: ['suspicious-downloads'],
              feedbackTitle: 'Good caution.',
              feedbackExplanation: 'IT can scan the drive safely. Even better: avoid USB drives entirely and use approved sharing tools.',
            },
          ],
        },
        {
          id: 'fc-3',
          scenario: 'You\'re leaving a meeting room and notice the whiteboard still has the client\'s architecture diagram and the meeting room screen shows an internal dashboard.',
          options: [
            {
              id: 'fc-3a',
              label: 'Erase the whiteboard and lock/close the screen',
              scoreImpact: 150,
              isCorrect: true,
              isBestPractice: true,
              topicTags: ['clean-desk', 'sensitive-data'],
              feedbackTitle: 'Perfect.',
              feedbackExplanation: 'Clearing sensitive info from shared spaces is everyone\'s responsibility.',
            },
            {
              id: 'fc-3b',
              label: 'Leave it — the next team will erase it',
              scoreImpact: -50,
              isCorrect: false,
              topicTags: ['clean-desk', 'sensitive-data'],
              feedbackTitle: 'Don\'t leave it to chance.',
              feedbackExplanation: 'The next people in the room might be visitors, clients, or contractors. Clean up confidential info before leaving.',
            },
            {
              id: 'fc-3c',
              label: 'Close the screen but leave the whiteboard',
              scoreImpact: 0,
              isCorrect: false,
              topicTags: ['clean-desk'],
              feedbackTitle: 'Half done.',
              feedbackExplanation: 'The whiteboard still shows client architecture details. Both need to be cleared.',
            },
          ],
        },
        {
          id: 'fc-4',
          scenario: 'A vendor emails asking you to export your team\'s customer contact list and send it to them for "integration testing."',
          options: [
            {
              id: 'fc-4a',
              label: 'Export and send it — they\'re a trusted vendor',
              scoreImpact: -50,
              isCorrect: false,
              topicTags: ['sensitive-data'],
              feedbackTitle: 'Don\'t send customer data externally without approval.',
              feedbackExplanation: 'Even trusted vendors should go through proper data-sharing agreements and approval processes.',
            },
            {
              id: 'fc-4b',
              label: 'Check with your manager and follow the data-sharing approval process',
              scoreImpact: 150,
              isCorrect: true,
              isBestPractice: true,
              topicTags: ['sensitive-data'],
              feedbackTitle: 'Correct process.',
              feedbackExplanation: 'Customer data should only be shared externally through approved channels with proper authorization.',
              takeaway: 'Always follow the approval process before sharing customer data externally.',
            },
            {
              id: 'fc-4c',
              label: 'Send a sample of 5 records instead of the full list',
              scoreImpact: 0,
              isCorrect: false,
              topicTags: ['sensitive-data'],
              feedbackTitle: 'Still needs approval.',
              feedbackExplanation: 'Even a small sample of customer data is sensitive and requires proper authorization to share externally.',
            },
          ],
        },
        {
          id: 'fc-5',
          scenario: 'Your phone shows a notification: "Your company account password was changed. If this wasn\'t you, take action now." You didn\'t change your password.',
          options: [
            {
              id: 'fc-5a',
              label: 'Immediately try to reset your password through the official portal and notify IT',
              scoreImpact: 150,
              isCorrect: true,
              isBestPractice: true,
              reportBonus: true,
              topicTags: ['credential-stuffing', 'mfa-methods'],
              feedbackTitle: 'Exactly right.',
              feedbackExplanation: 'A password change you didn\'t make means someone else has access. Reset immediately and alert your security team.',
            },
            {
              id: 'fc-5b',
              label: 'Click the link in the notification to investigate',
              scoreImpact: -50,
              isCorrect: false,
              topicTags: ['phishing'],
              feedbackTitle: 'The notification itself could be phishing.',
              feedbackExplanation: 'Go directly to your account portal — don\'t click links in notifications. This could be a fake alert designed to capture your credentials.',
            },
            {
              id: 'fc-5c',
              label: 'Wait and see if anything else happens',
              scoreImpact: 0,
              isCorrect: false,
              topicTags: ['credential-stuffing'],
              feedbackTitle: 'Too slow.',
              feedbackExplanation: 'If someone changed your password, they may already be in your account. Every minute of delay gives them more access.',
            },
          ],
        },
        {
          id: 'fc-6',
          scenario: 'A new app your team wants to use isn\'t in the company\'s approved software list, but it looks very useful.',
          options: [
            {
              id: 'fc-6a',
              label: 'Download it anyway — you\'ll tell IT later',
              scoreImpact: -50,
              isCorrect: false,
              topicTags: ['approved-software'],
              feedbackTitle: 'Always get approval first.',
              feedbackExplanation: 'Unapproved software can introduce security vulnerabilities, data leaks, and compliance issues.',
            },
            {
              id: 'fc-6b',
              label: 'Submit a request through the software approval process',
              scoreImpact: 150,
              isCorrect: true,
              isBestPractice: true,
              topicTags: ['approved-software'],
              feedbackTitle: 'Correct approach.',
              feedbackExplanation: 'The approval process ensures software meets security and compliance standards before it touches company data.',
            },
            {
              id: 'fc-6c',
              label: 'Use the web version without downloading anything',
              scoreImpact: 0,
              isCorrect: false,
              topicTags: ['approved-software'],
              feedbackTitle: 'Still needs approval.',
              feedbackExplanation: 'Web apps can still access sensitive data. The approval process applies to all new tools, not just installed software.',
            },
          ],
        },
      ],
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// Export all modules
// ═══════════════════════════════════════════════════════════════════════════════

export const ALL_MODULES: TrainingModule[] = [
  module1,
  module2,
  module3,
  module4,
  module5,
  finalChallenge,
];

export const MODULE_IDS = ALL_MODULES.map(m => m.id);

export function getModuleById(id: string): TrainingModule | undefined {
  return ALL_MODULES.find(m => m.id === id);
}
