import { RiskLevel } from '@/services/api/types';
import type {
  ControlTestDefinition,
  EvidenceSnapshotRecord,
  IntegrationJobExecutionRecord,
  NormalizedSignal,
  ProviderSyncStatusRecord,
  RiskEngineEventRecord,
  RiskRuleRecord,
  ScanRunRecord,
  SignalIngestionRecord,
} from './types';

const now = new Date();

function daysAgo(days: number) {
  const value = new Date(now);
  value.setDate(value.getDate() - days);
  return value.toISOString();
}

export const seedSignals: NormalizedSignal[] = [
  {
    id: 'sig-github-repo-private',
    organizationId: 'org_1',
    integrationId: 'int_github_core',
    provider: 'github',
    signalType: 'SOURCE_CODE_REPO_PRIVATE',
    resourceType: 'repository',
    resourceId: 'repo_manzen_app',
    resourceName: 'Manzen',
    value: false,
    metadata: { defaultBranch: 'main', branchProtection: false },
    observedAt: daysAgo(2),
    collectedAt: daysAgo(2),
  },
  {
    id: 'sig-github-branch-protection',
    organizationId: 'org_1',
    integrationId: 'int_github_core',
    provider: 'github',
    signalType: 'SOURCE_CODE_BRANCH_PROTECTION_ENABLED',
    resourceType: 'repository',
    resourceId: 'repo_manzen_app',
    resourceName: 'Manzen',
    value: false,
    metadata: { defaultBranch: 'main', requiredStatusChecks: false },
    observedAt: daysAgo(2),
    collectedAt: daysAgo(2),
  },
  {
    id: 'sig-github-required-reviews',
    organizationId: 'org_1',
    integrationId: 'int_github_core',
    provider: 'github',
    signalType: 'SOURCE_CODE_REQUIRED_REVIEWS_ENABLED',
    resourceType: 'repository',
    resourceId: 'repo_manzen_app',
    resourceName: 'Manzen',
    value: false,
    metadata: { requiredApprovingReviewCount: 0 },
    observedAt: daysAgo(2),
    collectedAt: daysAgo(2),
  },
  {
    id: 'sig-github-secret-scanning',
    organizationId: 'org_1',
    integrationId: 'int_github_core',
    provider: 'github',
    signalType: 'SOURCE_CODE_SECRET_SCANNING_ENABLED',
    resourceType: 'repository',
    resourceId: 'repo_manzen_app',
    resourceName: 'Manzen',
    value: false,
    metadata: { secretScanning: false, pushProtection: false },
    observedAt: daysAgo(2),
    collectedAt: daysAgo(2),
  },
  {
    id: 'sig-github-default-branch',
    organizationId: 'org_1',
    integrationId: 'int_github_core',
    provider: 'github',
    signalType: 'SOURCE_CODE_DEFAULT_BRANCH_STANDARD',
    resourceType: 'repository',
    resourceId: 'repo_manzen_app',
    resourceName: 'Manzen',
    value: true,
    metadata: { defaultBranch: 'main' },
    observedAt: daysAgo(2),
    collectedAt: daysAgo(2),
  },
  {
    id: 'sig-cloudflare-waf-zone',
    organizationId: 'org_1',
    integrationId: 'int_cloudflare_core',
    provider: 'cloudflare',
    signalType: 'NETWORK_WAF_ENABLED',
    resourceType: 'application',
    resourceId: 'cf-zone-app',
    resourceName: 'app.manzen.io',
    value: false,
    metadata: { zoneName: 'app.manzen.io' },
    observedAt: daysAgo(3),
    collectedAt: daysAgo(3),
  },
  {
    id: 'sig-aws-bucket-public',
    organizationId: 'org_1',
    integrationId: 'int_aws_prod',
    provider: 'aws',
    signalType: 'CLOUD_STORAGE_PUBLIC_ACCESS',
    resourceType: 'bucket',
    resourceId: 'bucket_prod_uploads',
    resourceName: 'prod-uploads',
    value: true,
    metadata: { accountId: '123456789012', region: 'us-east-1' },
    observedAt: daysAgo(10),
    collectedAt: daysAgo(10),
  },
  {
    id: 'sig-okta-mfa-admin',
    organizationId: 'org_1',
    integrationId: 'int_okta_core',
    provider: 'okta',
    signalType: 'IDENTITY_MFA_ENABLED',
    resourceType: 'identity',
    resourceId: 'user_admin_1',
    resourceName: 'admin@manzen.io',
    value: false,
    metadata: { role: 'SUPER_ADMIN' },
    observedAt: daysAgo(5),
    collectedAt: daysAgo(5),
  },
  {
    id: 'sig-snyk-critical-vuln',
    organizationId: 'org_1',
    integrationId: 'int_snyk_appsec',
    provider: 'snyk',
    signalType: 'VULNERABILITY_CRITICAL_OPEN',
    resourceType: 'repository',
    resourceId: 'repo_payments_api',
    resourceName: 'payments-api',
    value: 3,
    metadata: { ageDays: 37 },
    observedAt: daysAgo(3),
    collectedAt: daysAgo(3),
  },
  {
    id: 'sig-fleet-encryption',
    organizationId: 'org_1',
    integrationId: 'int_fleet_devices',
    provider: 'fleet',
    signalType: 'DEVICE_DISK_ENCRYPTED',
    resourceType: 'device',
    resourceId: 'device_macbook_114',
    resourceName: 'MacBook-Pro-114',
    value: false,
    metadata: { serial: 'C02ABCXYZ' },
    observedAt: daysAgo(1),
    collectedAt: daysAgo(1),
  },
];

export const seedTests: ControlTestDefinition[] = [
  {
    id: 'test-public-storage',
    controlId: 'control-cloud-storage-private',
    controlName: 'Production storage must not be public',
    version: 1,
    signalType: 'CLOUD_STORAGE_PUBLIC_ACCESS',
    name: 'S3 public access disabled',
    description: 'Fail when any production storage bucket is publicly accessible.',
    frameworkIds: ['SOC2-CC6.1', 'ISO27001-A.8.9'],
    severityOnFail: RiskLevel.CRITICAL,
    condition: { operator: 'equals', expected: false },
  },
  {
    id: 'test-admin-mfa',
    controlId: 'control-admin-mfa',
    controlName: 'MFA enforced for privileged identities',
    version: 1,
    signalType: 'IDENTITY_MFA_ENABLED',
    name: 'Privileged MFA enabled',
    description: 'Fail when privileged users do not have MFA enabled.',
    frameworkIds: ['SOC2-CC6.2', 'ISO27001-A.5.17'],
    severityOnFail: RiskLevel.CRITICAL,
    condition: { operator: 'equals', expected: true },
  },
  {
    id: 'test-critical-vuln-age',
    controlId: 'control-vulnerability-sla',
    controlName: 'Critical vulnerabilities remediated in SLA',
    version: 1,
    signalType: 'VULNERABILITY_CRITICAL_OPEN',
    name: 'Critical vulnerabilities older than threshold',
    description: 'Fail when critical open vulnerability count is greater than zero.',
    frameworkIds: ['SOC2-CC7.1', 'ISO27001-A.8.28'],
    severityOnFail: RiskLevel.HIGH,
    condition: { operator: 'less_than', expected: 1 },
  },
  {
    id: 'test-disk-encryption',
    controlId: 'control-disk-encryption',
    controlName: 'Managed endpoints require disk encryption',
    version: 1,
    signalType: 'DEVICE_DISK_ENCRYPTED',
    name: 'Disk encryption enabled',
    description: 'Fail when a managed endpoint reports disk encryption disabled.',
    frameworkIds: ['SOC2-CC6.7', 'ISO27001-A.8.1'],
    severityOnFail: RiskLevel.MEDIUM,
    condition: { operator: 'equals', expected: true },
  },
  {
    id: 'test-github-private-repo',
    controlId: 'control-repository-privacy',
    controlName: 'Source repositories must be private',
    version: 1,
    signalType: 'SOURCE_CODE_REPO_PRIVATE',
    name: 'GitHub repositories private',
    description: 'Fail when an organizational GitHub repository is publicly visible.',
    frameworkIds: ['SOC2-CC6.6', 'ISO27001-A.8.32'],
    severityOnFail: RiskLevel.HIGH,
    condition: { operator: 'equals', expected: true },
  },
  {
    id: 'test-github-branch-protection',
    controlId: 'control-branch-protection',
    controlName: 'Default branches require branch protection',
    version: 1,
    signalType: 'SOURCE_CODE_BRANCH_PROTECTION_ENABLED',
    name: 'GitHub branch protection enabled',
    description: 'Fail when a repository default branch is not protected.',
    frameworkIds: ['SOC2-CC7.2', 'ISO27001-A.8.25'],
    severityOnFail: RiskLevel.HIGH,
    condition: { operator: 'equals', expected: true },
  },
  {
    id: 'test-github-required-reviews',
    controlId: 'control-required-reviews',
    controlName: 'Pull requests require peer review',
    version: 1,
    signalType: 'SOURCE_CODE_REQUIRED_REVIEWS_ENABLED',
    name: 'GitHub required reviews enabled',
    description: 'Fail when pull requests do not require approving reviews.',
    frameworkIds: ['SOC2-CC7.2', 'ISO27001-A.8.25'],
    severityOnFail: RiskLevel.MEDIUM,
    condition: { operator: 'equals', expected: true },
  },
  {
    id: 'test-github-secret-scanning',
    controlId: 'control-secret-scanning',
    controlName: 'Secret scanning is enabled',
    version: 1,
    signalType: 'SOURCE_CODE_SECRET_SCANNING_ENABLED',
    name: 'GitHub secret scanning enabled',
    description: 'Fail when repository secret scanning is disabled.',
    frameworkIds: ['SOC2-CC6.7', 'ISO27001-A.8.28'],
    severityOnFail: RiskLevel.HIGH,
    condition: { operator: 'equals', expected: true },
  },
  {
    id: 'test-github-default-branch',
    controlId: 'control-default-branch-standard',
    controlName: 'Repositories use a standard default branch',
    version: 1,
    signalType: 'SOURCE_CODE_DEFAULT_BRANCH_STANDARD',
    name: 'GitHub default branch standard',
    description: 'Warn or fail when repositories do not use the standard protected branch.',
    frameworkIds: ['SOC2-CC7.2'],
    severityOnFail: RiskLevel.MEDIUM,
    condition: { operator: 'equals', expected: true },
  },
  {
    id: 'test-cloudflare-waf-enabled',
    controlId: 'control-network-waf',
    controlName: 'External applications require WAF',
    version: 1,
    signalType: 'NETWORK_WAF_ENABLED',
    name: 'Cloudflare WAF enabled',
    description: 'Fail when WAF protections are disabled on externally exposed applications.',
    frameworkIds: ['SOC2-CC6.6', 'ISO27001-A.8.20'],
    severityOnFail: RiskLevel.HIGH,
    condition: { operator: 'equals', expected: true },
  },
];

export const seedRules: RiskRuleRecord[] = [
  {
    id: 'rule-cloud-public-access',
    name: 'Public cloud exposure',
    signalType: 'CLOUD_STORAGE_PUBLIC_ACCESS',
    category: 'Cloud',
    defaultLikelihood: RiskLevel.HIGH,
    severityWeight: 100,
    assetCriticalityWeight: 50,
    durationWeight: 2,
  },
  {
    id: 'rule-identity-mfa-gap',
    name: 'Privileged identity hardening gap',
    signalType: 'IDENTITY_MFA_ENABLED',
    category: 'Identity',
    defaultLikelihood: RiskLevel.MEDIUM,
    severityWeight: 100,
    assetCriticalityWeight: 45,
    durationWeight: 2,
  },
  {
    id: 'rule-critical-vulnerability',
    name: 'Critical vulnerability overdue',
    signalType: 'VULNERABILITY_CRITICAL_OPEN',
    category: 'Application',
    defaultLikelihood: RiskLevel.HIGH,
    severityWeight: 75,
    assetCriticalityWeight: 40,
    durationWeight: 1,
  },
  {
    id: 'rule-endpoint-encryption',
    name: 'Disk encryption drift',
    signalType: 'DEVICE_DISK_ENCRYPTED',
    category: 'Endpoint',
    defaultLikelihood: RiskLevel.MEDIUM,
    severityWeight: 50,
    assetCriticalityWeight: 20,
    durationWeight: 1,
  },
  {
    id: 'rule-github-repository-exposure',
    name: 'Repository visibility exposure',
    signalType: 'SOURCE_CODE_REPO_PRIVATE',
    category: 'Application',
    defaultLikelihood: RiskLevel.MEDIUM,
    severityWeight: 75,
    assetCriticalityWeight: 35,
    durationWeight: 1,
  },
  {
    id: 'rule-github-branch-protection',
    name: 'Branch protection drift',
    signalType: 'SOURCE_CODE_BRANCH_PROTECTION_ENABLED',
    category: 'Application',
    defaultLikelihood: RiskLevel.MEDIUM,
    severityWeight: 75,
    assetCriticalityWeight: 30,
    durationWeight: 1,
  },
  {
    id: 'rule-github-required-reviews',
    name: 'Required review drift',
    signalType: 'SOURCE_CODE_REQUIRED_REVIEWS_ENABLED',
    category: 'Application',
    defaultLikelihood: RiskLevel.MEDIUM,
    severityWeight: 50,
    assetCriticalityWeight: 25,
    durationWeight: 1,
  },
  {
    id: 'rule-github-secret-scanning',
    name: 'Secret scanning disabled',
    signalType: 'SOURCE_CODE_SECRET_SCANNING_ENABLED',
    category: 'Application',
    defaultLikelihood: RiskLevel.HIGH,
    severityWeight: 75,
    assetCriticalityWeight: 30,
    durationWeight: 1,
  },
  {
    id: 'rule-github-default-branch',
    name: 'Default branch standard drift',
    signalType: 'SOURCE_CODE_DEFAULT_BRANCH_STANDARD',
    category: 'Application',
    defaultLikelihood: RiskLevel.LOW,
    severityWeight: 50,
    assetCriticalityWeight: 15,
    durationWeight: 1,
  },
  {
    id: 'rule-cloudflare-waf',
    name: 'WAF protection disabled',
    signalType: 'NETWORK_WAF_ENABLED',
    category: 'Network',
    defaultLikelihood: RiskLevel.HIGH,
    severityWeight: 75,
    assetCriticalityWeight: 30,
    durationWeight: 1,
  },
];

export const seedEvidence: EvidenceSnapshotRecord[] = [
  {
    id: 'ev-aws-public-bucket',
    organizationId: 'org_1',
    kind: 'signal',
    provider: 'aws',
    integrationId: 'int_aws_prod',
    resourceId: 'bucket_prod_uploads',
    hash: 'sha256:awsbucketpublic001',
    capturedAt: daysAgo(10),
    payload: { public: true, blockPublicAcls: false },
  },
  {
    id: 'ev-okta-admin-mfa',
    organizationId: 'org_1',
    kind: 'signal',
    provider: 'okta',
    integrationId: 'int_okta_core',
    resourceId: 'user_admin_1',
    hash: 'sha256:oktamfa002',
    capturedAt: daysAgo(5),
    payload: { mfaEnabled: false, factorCount: 0 },
  },
];

export const seedProviderStatuses: ProviderSyncStatusRecord[] = [
  {
    id: 'provider-aws',
    provider: 'aws',
    integrationId: 'int_aws_prod',
    status: 'HEALTHY',
    lastSyncAt: daysAgo(1),
    lastSuccessAt: daysAgo(1),
    signalsCollected: 12,
    testsEvaluated: 4,
    openRisks: 1,
  },
  {
    id: 'provider-okta',
    provider: 'okta',
    integrationId: 'int_okta_core',
    status: 'HEALTHY',
    lastSyncAt: daysAgo(0),
    lastSuccessAt: daysAgo(0),
    signalsCollected: 8,
    testsEvaluated: 2,
    openRisks: 1,
  },
  {
    id: 'provider-snyk',
    provider: 'snyk',
    integrationId: 'int_snyk_appsec',
    status: 'DEGRADED',
    lastSyncAt: daysAgo(2),
    lastSuccessAt: daysAgo(3),
    signalsCollected: 5,
    testsEvaluated: 1,
    openRisks: 1,
  },
  {
    id: 'provider-fleet',
    provider: 'fleet',
    integrationId: 'int_fleet_devices',
    status: 'HEALTHY',
    lastSyncAt: daysAgo(0),
    lastSuccessAt: daysAgo(0),
    signalsCollected: 14,
    testsEvaluated: 3,
    openRisks: 1,
  },
  {
    id: 'provider-github',
    provider: 'github',
    integrationId: 'int_github_core',
    status: 'HEALTHY',
    lastSyncAt: daysAgo(2),
    lastSuccessAt: daysAgo(2),
    signalsCollected: 1,
    testsEvaluated: 1,
    openRisks: 1,
  },
];

export const seedScanRuns: ScanRunRecord[] = [
  {
    id: 'scan-1',
    provider: 'aws',
    integrationId: 'int_aws_prod',
    startedAt: daysAgo(1),
    completedAt: daysAgo(1),
    status: 'SUCCEEDED',
    signalsIngested: 12,
    testsExecuted: 4,
    risksGenerated: 1,
    trigger: 'scheduled',
  },
  {
    id: 'scan-2',
    provider: 'okta',
    integrationId: 'int_okta_core',
    startedAt: daysAgo(0),
    completedAt: daysAgo(0),
    status: 'SUCCEEDED',
    signalsIngested: 8,
    testsExecuted: 2,
    risksGenerated: 1,
    trigger: 'webhook',
  },
  {
    id: 'scan-3',
    provider: 'snyk',
    integrationId: 'int_snyk_appsec',
    startedAt: daysAgo(2),
    completedAt: daysAgo(2),
    status: 'FAILED',
    signalsIngested: 2,
    testsExecuted: 1,
    risksGenerated: 0,
    trigger: 'scheduled',
  },
  {
    id: 'scan-4',
    provider: 'fleet',
    integrationId: 'int_fleet_devices',
    startedAt: daysAgo(0),
    completedAt: daysAgo(0),
    status: 'SUCCEEDED',
    signalsIngested: 14,
    testsExecuted: 3,
    risksGenerated: 1,
    trigger: 'manual',
  },
  {
    id: 'scan-github-1',
    provider: 'github',
    integrationId: 'int_github_core',
    startedAt: daysAgo(2),
    completedAt: daysAgo(2),
    status: 'SUCCEEDED',
    signalsIngested: 1,
    testsExecuted: 1,
    risksGenerated: 1,
    trigger: 'scheduled',
  },
];

export const seedEvents: RiskEngineEventRecord[] = [
  {
    id: 'event-1',
    eventType: 'integration.sync.completed',
    provider: 'aws',
    integrationId: 'int_aws_prod',
    organizationId: 'org_1',
    resourceId: 'bucket_prod_uploads',
    severity: 'info',
    message: 'AWS collector sync completed successfully for production account.',
    createdAt: daysAgo(1),
    metadata: { scanRunId: 'scan-1', signalsIngested: 12 },
  },
  {
    id: 'event-2',
    eventType: 'signal.ingested',
    provider: 'okta',
    integrationId: 'int_okta_core',
    organizationId: 'org_1',
    resourceId: 'user_admin_1',
    severity: 'warning',
    message: 'Privileged identity signal ingested with MFA disabled.',
    createdAt: daysAgo(0),
    metadata: { signalId: 'sig-okta-mfa-admin' },
  },
  {
    id: 'event-3',
    eventType: 'test.failed',
    provider: 'snyk',
    integrationId: 'int_snyk_appsec',
    organizationId: 'org_1',
    resourceId: 'repo_payments_api',
    severity: 'critical',
    message: 'Critical vulnerability SLA test failed for payments-api.',
    createdAt: daysAgo(0),
    metadata: { testId: 'test-critical-vuln-age' },
  },
  {
    id: 'event-4',
    eventType: 'risk.created',
    provider: 'system',
    integrationId: 'risk-engine-foundation',
    organizationId: 'org_1',
    resourceId: 'bucket_prod_uploads',
    severity: 'critical',
    message: 'Risk created for public production storage exposure.',
    createdAt: daysAgo(0),
    metadata: { riskId: 'risk-rule-cloud-public-access-bucket_prod_uploads' },
  },
  {
    id: 'event-5',
    eventType: 'evidence.created',
    provider: 'aws',
    integrationId: 'int_aws_prod',
    organizationId: 'org_1',
    resourceId: 'bucket_prod_uploads',
    severity: 'info',
    message: 'Evidence snapshot stored for public bucket finding.',
    createdAt: daysAgo(0),
    metadata: { evidenceId: 'ev-aws-public-bucket' },
  },
  {
    id: 'event-6',
    eventType: 'signal.normalized',
    provider: 'github',
    integrationId: 'int_github_core',
    organizationId: 'org_1',
    resourceId: 'repo_manzen_app',
    severity: 'warning',
    message: 'GitHub repository visibility signal normalized for Manzen.',
    createdAt: daysAgo(2),
    metadata: { signalId: 'sig-github-repo-private' },
  },
];

export const seedIntegrationExecutions: IntegrationJobExecutionRecord[] = [
  {
    id: 'job-aws-sync-1',
    provider: 'aws',
    integrationId: 'int_aws_prod',
    organizationId: 'org_1',
    jobType: 'sync',
    status: 'SUCCEEDED',
    startedAt: daysAgo(1),
    completedAt: daysAgo(1),
    metadata: { scanRunId: 'scan-1' },
  },
  {
    id: 'job-okta-sync-1',
    provider: 'okta',
    integrationId: 'int_okta_core',
    organizationId: 'org_1',
    jobType: 'sync',
    status: 'SUCCEEDED',
    startedAt: daysAgo(0),
    completedAt: daysAgo(0),
    metadata: { scanRunId: 'scan-2' },
  },
  {
    id: 'job-snyk-sync-1',
    provider: 'snyk',
    integrationId: 'int_snyk_appsec',
    organizationId: 'org_1',
    jobType: 'scan',
    status: 'FAILED',
    startedAt: daysAgo(2),
    completedAt: daysAgo(2),
    errorMessage: 'Timed out while fetching findings from Snyk API.',
    metadata: { scanRunId: 'scan-3' },
  },
  {
    id: 'job-github-sync-1',
    provider: 'github',
    integrationId: 'int_github_core',
    organizationId: 'org_1',
    jobType: 'sync',
    status: 'SUCCEEDED',
    startedAt: daysAgo(2),
    completedAt: daysAgo(2),
    metadata: { scanRunId: 'scan-github-1' },
  },
];

export const seedSignalIngestions: SignalIngestionRecord[] = [
  {
    id: 'ingest-1',
    signalId: 'sig-aws-bucket-public',
    provider: 'aws',
    integrationId: 'int_aws_prod',
    organizationId: 'org_1',
    resourceId: 'bucket_prod_uploads',
    ingestedAt: daysAgo(1),
    normalizedAt: daysAgo(1),
    jobExecutionId: 'job-aws-sync-1',
  },
  {
    id: 'ingest-2',
    signalId: 'sig-okta-mfa-admin',
    provider: 'okta',
    integrationId: 'int_okta_core',
    organizationId: 'org_1',
    resourceId: 'user_admin_1',
    ingestedAt: daysAgo(0),
    normalizedAt: daysAgo(0),
    jobExecutionId: 'job-okta-sync-1',
  },
  {
    id: 'ingest-3',
    signalId: 'sig-github-repo-private',
    provider: 'github',
    integrationId: 'int_github_core',
    organizationId: 'org_1',
    resourceId: 'repo_manzen_app',
    ingestedAt: daysAgo(2),
    normalizedAt: daysAgo(2),
    jobExecutionId: 'job-github-sync-1',
  },
];
