import { testsContracts } from './contracts';

export const testsRoutes = [
  { method: 'GET', url: testsContracts.listTests.path, handlerName: 'listTests', schema: { response: testsContracts.listTests.response } },
  { method: 'GET', url: testsContracts.getSummary.path, handlerName: 'getSummary', schema: { response: testsContracts.getSummary.response } },
  { method: 'GET', url: testsContracts.getDashboard.path, handlerName: 'getDashboard', schema: { response: testsContracts.getDashboard.response } },
  { method: 'GET', url: testsContracts.getGapAnalysis.path, handlerName: 'getGapAnalysis', schema: { response: testsContracts.getGapAnalysis.response } },
  { method: 'GET', url: testsContracts.listTemplates.path, handlerName: 'listTemplates', schema: { response: testsContracts.listTemplates.response } },
  { method: 'GET', url: testsContracts.exportTests.path, handlerName: 'exportTests', schema: { response: testsContracts.exportTests.response } },
  { method: 'GET', url: testsContracts.listSecurityEvents.path, handlerName: 'listSecurityEvents', schema: { response: testsContracts.listSecurityEvents.response } },
  { method: 'GET', url: testsContracts.listUnifiedEvidence.path, handlerName: 'listUnifiedEvidence', schema: { response: testsContracts.listUnifiedEvidence.response } },
  { method: 'GET', url: testsContracts.listEscalations.path, handlerName: 'listEscalations', schema: { response: testsContracts.listEscalations.response } },
  { method: 'POST', url: testsContracts.ingestPipelineRun.path, handlerName: 'ingestPipelineRun', schema: { body: testsContracts.ingestPipelineRun.body, response: testsContracts.ingestPipelineRun.response } },
  { method: 'POST', url: testsContracts.createSuiteFromTemplate.path, handlerName: 'createSuiteFromTemplate', schema: { response: testsContracts.createSuiteFromTemplate.response } },
  { method: 'GET', url: testsContracts.getTest.path, handlerName: 'getTest', schema: { response: testsContracts.getTest.response } },
  { method: 'POST', url: testsContracts.createTest.path, handlerName: 'createTest', schema: { body: testsContracts.createTest.body, response: testsContracts.createTest.response } },
  { method: 'PUT', url: testsContracts.updateTest.path, handlerName: 'updateTest', schema: { body: testsContracts.updateTest.body, response: testsContracts.updateTest.response } },
  { method: 'DELETE', url: testsContracts.deleteTest.path, handlerName: 'deleteTest', schema: { response: testsContracts.deleteTest.response } },
  { method: 'POST', url: testsContracts.completeTest.path, handlerName: 'completeTest', schema: { response: testsContracts.completeTest.response } },
  { method: 'POST', url: testsContracts.attachEvidence.path, handlerName: 'attachEvidence', schema: { body: testsContracts.attachEvidence.body, response: testsContracts.attachEvidence.response } },
  { method: 'DELETE', url: testsContracts.detachEvidence.path, handlerName: 'detachEvidence', schema: { response: testsContracts.detachEvidence.response } },
  { method: 'POST', url: testsContracts.attachControl.path, handlerName: 'attachControl', schema: { body: testsContracts.attachControl.body, response: testsContracts.attachControl.response } },
  { method: 'DELETE', url: testsContracts.detachControl.path, handlerName: 'detachControl', schema: { response: testsContracts.detachControl.response } },
  { method: 'POST', url: testsContracts.attachAudit.path, handlerName: 'attachAudit', schema: { body: testsContracts.attachAudit.body, response: testsContracts.attachAudit.response } },
  { method: 'DELETE', url: testsContracts.detachAudit.path, handlerName: 'detachAudit', schema: { response: testsContracts.detachAudit.response } },
  { method: 'POST', url: testsContracts.attachFramework.path, handlerName: 'attachFramework', schema: { body: testsContracts.attachFramework.body, response: testsContracts.attachFramework.response } },
  { method: 'DELETE', url: testsContracts.detachFramework.path, handlerName: 'detachFramework', schema: { response: testsContracts.detachFramework.response } },
  { method: 'GET', url: testsContracts.getHistory.path, handlerName: 'getHistory', schema: { response: testsContracts.getHistory.response } },
  { method: 'POST', url: testsContracts.seedTests.path, handlerName: 'seedTests', schema: { response: testsContracts.seedTests.response } },
  { method: 'GET', url: testsContracts.getRuns.path, handlerName: 'getRuns', schema: { response: testsContracts.getRuns.response } },
  { method: 'GET', url: testsContracts.getRiskContext.path, handlerName: 'getRiskContext', schema: { response: testsContracts.getRiskContext.response } },
  { method: 'POST', url: testsContracts.requestAttestation.path, handlerName: 'requestAttestation', schema: { body: testsContracts.requestAttestation.body, response: testsContracts.requestAttestation.response } },
  { method: 'POST', url: testsContracts.signAttestation.path, handlerName: 'signAttestation', schema: { body: testsContracts.signAttestation.body, response: testsContracts.signAttestation.response } },
  { method: 'POST', url: testsContracts.autoRemediate.path, handlerName: 'autoRemediate', schema: { response: testsContracts.autoRemediate.response } },
  { method: 'POST', url: testsContracts.bulkComplete.path, handlerName: 'bulkComplete', schema: { body: testsContracts.bulkComplete.body, response: testsContracts.bulkComplete.response } },
  { method: 'POST', url: testsContracts.bulkAssign.path, handlerName: 'bulkAssign', schema: { body: testsContracts.bulkAssign.body, response: testsContracts.bulkAssign.response } },
  { method: 'POST', url: testsContracts.bulkLinkControl.path, handlerName: 'bulkLinkControl', schema: { body: testsContracts.bulkLinkControl.body, response: testsContracts.bulkLinkControl.response } },
] as const;
